### ISSUE TITLE
As an Administrator I want to be able to assign different roles to different doctors/health officials/immigration officers so that every user has a specific role.

### ISSUE THREAD

**Issue by gfdb** [gfdb/soen390#22]

**Comment by davrine** [comment]
## description
Back-end

**Comment by Cresfault** [comment]
@gfdb This tasks seems redundant now, since #38 that I have with Mohamad to approve doctors, nurses, etc... will automatically place them in the database table. So approved doctors are in the Doctors table and health officials in the Health Officials table for example. 
Therefore the only thing this task could be good for is changing roles, so changing a doctor to a health official for example, but this seems like it would cause unnecessary issues since we would essentially be changing a hospital worker into government official. So I'm thinking we remove/merge this task into #38 , what do you think?
